# Generated by Django 2.0.9 on 2018-11-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prom_encuestas', models.IntegerField(default=0)),
                ('t_nombre', models.CharField(max_length=200)),
                ('t_apellido', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('placas', models.CharField(max_length=200)),
                ('lista_permisos', models.BooleanField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('destino', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=200)),
                ('taxi_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Taxi')),
            ],
        ),
    ]
