# Generated by Django 2.0.9 on 2018-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_viaje_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(max_length=50)),
                ('respuesta1_p1', models.CharField(max_length=20)),
                ('respuesta2_p1', models.CharField(max_length=20)),
                ('respuesta3_p1', models.CharField(max_length=20)),
                ('pregunta2', models.CharField(max_length=50)),
                ('respuesta1_p2', models.CharField(max_length=20)),
                ('respuesta2_p2', models.CharField(max_length=20)),
                ('respuesta3_p2', models.CharField(max_length=20)),
                ('pregunta3', models.CharField(max_length=50)),
                ('respuesta1_p3', models.CharField(max_length=20)),
                ('respuesta2_p3', models.CharField(max_length=20)),
                ('respuesta3_p3', models.CharField(max_length=20)),
            ],
        ),
    ]
