# Generated by Django 2.0.9 on 2018-11-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_encuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encuesta',
        ),
    ]
